config/routes.rb
CourseTracker::Application.routes.draw do

  resources :documents

  resources :semesters

  resources :enrollments do
    collection { post :import }
  end  

  resources :courses

  devise_for :users

  resources :users, only: [:show, :index] do
    resources :courses
    end  

    resources :courses do
      resources :refrences
    end

  root 'pages#index'

end

app/controllers/courses_controller.rb
class CoursesController < ApplicationController

  def show
    if current_user
      @user = current_user
      @course = Course.find(params[:id])
      @students = []
      @grades = []
      Enrollment.where(course_id: @course.id).each do |enrollment|
        @students << User.find_by(id: enrollment.student_id)
        @grades << enrollment.grade
      end
      @students = Kaminari.paginate_array(@students).page(params[:page]).per(6)
      if @grades.empty?
        @average = "There are no enrollments for this course. Why don't you upload some?"
      else
        @average = (@grades.sum/@grades.count).round(2)
      end
    elsif
      redirect_to root_path, notice: 'You need to sign in to see this page'
    end
  end

  def index
    if current_user
      @user = current_user
      @user_courses = @user.courses.page(params[:page]).per(6)
      @all_courses = Course.all.page(params[:page]).per(6)
    else
      redirect_to root_path, notice: 'You need to sign in to see this page'
    end
  end 

  def edit
    @course = Course.find(params[:id])
  end

  def update
    @course = Course.find(params[:id])
    if @course.update_attributes(params[:refrence])
      flash[:notice] = 'Successfully updated course files.'
      redirect_to courses_path(@course)
    else
      render action: 'edit'
    end
  end

  private

  def course_params
    params.require(:course).permit(:title, :semester_id, :teacher_id, :refrence)
  end
end

app/views/courses/index.html.erb
<% if @user.role =='Teacher' %>
  <div class="row">
    <div class="large-6 columns">
      <h2 class="header">My Courses</h2>
        <table class="table">
        <div class="header"><%= paginate @user_courses %></div>
          <thead>
            <tr>
              <th>Course Title</th>
              <th>Semester</th>
            </tr>
          </thead>
          <tbody>
            <% @user_courses.each do |course| %>
              <tr>
                <td><%= link_to course.title, course_path(course) %></td>
                <td><%= course.semester.name if course.semester %></td>
              </tr>
            <% end %>
          </tbody>
        </table>
    </div>
    <div class="large-6 columns">
      <h2 class="header">All Courses Offered</h1>
        <table class="table">
          <div class="header"><%= paginate @all_courses %></div>
            <thead>
              <tr>
                <th>Course Title</th>
                <th>Semester<th>
              </tr>
            </thead>
            <tbody>
              <% @all_courses.each do |course| %>
                <tr>
                  <td><%= course.title %></td>
                  <td><%= course.semester.name if course.semester %></td>
                </tr>
              <% end %>
            </tbody>
        </table>
    </div>
  </div>

<% elsif @user.role == 'Student'%>
  <h2 class="header">Courses Offered</h2>
    <table class="table">
      <div class="header"><%= paginate @all_courses %></div>
        <thead>
          <tr>
            <th class="header">Course Title</th>
            <th class="header">Semester</th>
          </tr>
        </thead>
        <tbody>
          <% @all_courses.each do |course| %>
            <tr>
              <td><%= course.title %></td>
              <td><%= course.semester.name %></td>
            </tr>
          <% end %>
        </tbody>
    </table>

<% else %>
  <h2 class="header">Courses</h2>
    <table class="table">
      <div class="header"><%= paginate @all_courses %></div>
        <thead>
          <tr>
            <th class="header">Course Title</th>
            <th class="header">Semester</th>
          </tr>
        </thead>
        <tbody>
          <% @all_courses.each do |course| %>
            <tr>
              <td><%= link_to course.title, course_path(course) %></td>
              <td><%= course.semester.name if course.semester%></td>
            </tr>
          <% end %>
        </tbody>
    </table>
<% end %>

<div class="back-button">
  <%= link_to 'Back', "users/#{@user.id}", class: "button" %>
</div>

app/views/courses/show.html.erb
<% if @user.role == 'Administrator' %>
  <h5 class="average">Average grade for <%= @course.title + ' ' %>(<%= @course.semester.name %>) is: </h5>
  <h7 class="average1"><%= @average %></h7>
  <h2 class="header">Course Roster</h1>
    <table class="table">
    <div class="header"><%= paginate @students %></div>
      <thead>
        <tr>
          <th class="header">Full Name</th>
          <th class="header">Student ID</th>
          <th class="header">Grade</th>
          <th class="header">Edit</th>
          <th class="header">Remove</th>
        </tr>
      </thead>
      <tbody>
        <% @students.each do |student| %>
        <% @enrollment = Enrollment.find_by(course_id: @course.id, student_id: student.id) %>
          <tr>
            <td><%= student.full_name %></td>
            <td><%= student.id %></td>
            <td><%= @enrollment.grade %></td>
            <td><%= link_to 'Edit', edit_enrollment_path(@enrollment) %></td>
            <td><%= link_to 'Remove', enrollment_path(@enrollment), method: :delete, data: { confirm: 'Are you sure?' } %></td>
          </tr>
        <% end %>
      </tbody>
    </table>
  <h5>Import Enrollments</h5>
    <%= form_tag import_enrollments_path, multipart: true do %>
      <%= file_field_tag :file %>
      <%= hidden_field_tag :course_id, @course.id %>
      <%= submit_tag 'Import' %>
    <% end %>	

<% elsif @user.role == 'Teacher' %>
  <div class="row">
    <div class="large-6 columns">
      <h2 class="header">Course Roster</h1>
        <table class="table">
          <div class="header"><%= paginate @students %></div>
          <thead>
            <tr>
            <th class="header">Full Name</th>
            <th class="header">Student ID</th>
            <th class="header">Grade</th>
            <th class="header">Edit</th>
            <th class="header">Remove</th>
            </tr>
          </thead>
          <tbody>
            <% @students.each do |student| %>
              <% @enrollment = Enrollment.find_by(course_id: @course.id, student_id: student.id) %>
              <tr>
                <td><%= student.full_name %></td>
                <td><%= student.id %></td>
                <td><%= @enrollment.grade %></td>
                <td><%= link_to 'Edit', edit_enrollment_path(@enrollment) %></td>
                <td><%= link_to 'Remove', enrollment_path(@enrollment), method: :delete, data: { confirm: 'Are you sure?' } %></td>
              </tr>
            <% end %>
          </tbody>
        </table>
      <h5>Import Enrollments</h5>
        <%= form_tag import_enrollments_path, multipart: true do %>
          <%= file_field_tag :file %>
          <%= hidden_field_tag :course_id, @course.id %>
          <%= submit_tag "Import" %>
        <% end %>
    </div>
    <div class="large-6 columns">
      <h2 class="header">Refrences</h1>			
        <table class="table">
          <thead>
            <th class="header">Download</th>
            <th class="header">File Name</th>
          </thead>
          <tbody>
            <tr>
              <% @course.refrences.each do |refrence|  %>
                <td><%= link_to image_tag(refrence.image.thumb('40x40#').url), refrence.image.url if refrence.image_stored? %></td>
                <td><%= refrence.name %></td>
            </tr> 
              <% end %>	 
          </tbody>
        </table>
      <%= link_to 'Add Refrence', new_course_refrence_path(@course) %>
    </div>
  </div>

<% else @user.role == 'Student' %>
  <div class="row">
    <div class="large-6 columns">
      <h2 class="header">Refrences</h1>			
      <table class="table">
        <thead>
          <tr>
            <th class="header">Download</th>
            <th class="header">File Name</th>
          </tr>
        </thead>
        <tbody>
        <tr>
          <% @course.refrences.each do |refrence| %>
            <td><%= link_to image_tag(refrence.thumb('40x40#').url), refrence.url if refrence.image_stored? %></td>
            <td><%= refrence.name %></td>	
        </tr>
        <% end %>
        </tbody>
      </table>
    </div>
  </div>
<% end %>


<div class="back-button">
  <%= link_to 'Back', courses_path, class: "button" %>
</div>